version: "3.1"

services:


  database:
    build: 
       context: ./database
    image: atsea_db
    command: postgres -c config_file=/usr/share/postgresql/9.6/postgresql.conf
    user: postgres
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: atsea
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432" 
    networks:
      - back-tier
    secrets:
      - postgres_password
    volumes: 
      - /mnt/logs/pg_log:/usr/share/postgresql/9.6/pg_log  

  appserver:
    build:
       context: app
       dockerfile: Dockerfile
    image: atsea_app
    user: gordon
    ports:
      - "8080:8080" 
      - "5005:5005"
    networks:
      - front-tier
      - back-tier
    secrets:
      - postgres_password
    volumes: 
      - /home/bishal-bi/new:/mnt/logs  
    container_name: appserver     

  reverse_proxy:
    build: ./reverse_proxy
    networks:
      - front-tier
    volumes: 
      - /home/bishal-bi/new/nginx:/var/log/nginx   

  payment_gateway:
    build:
      context: payment_gateway
    networks:
      - payment
    secrets:
      - payment_token

networks:
  front-tier: 
  back-tier: 
  payment:
    driver: overlay  
    

secrets:
  postgres_password:
    file: ./devsecrets/postgres_password
  payment_token:
    file: ./devsecrets/payment_token
