version: "3.1"

services:


  database:
    build: 
       context: ./database
    image: atsea_db
    command: postgres -c config_file=/usr/share/postgresql/9.6/postgresql.conf
    user: postgres
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: atsea
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432" 
    networks:
      - back-tier
    secrets:
      - postgres_password
    volumes: 
      - /mnt/logs/pg_log:/usr/share/postgresql/9.6/pg_log

  appserver:
    build:
       context: app
       dockerfile: Dockerfile
    image: atsea_app
    user: gordon
    ports:
      - "8080:8080" 
      - "5005:5005"
      - "9011:9011"
    networks:
      - front-tier
      - back-tier
    secrets:
      - postgres_password
    volumes: 
      - /mnt/logs/app_server:/mnt/logs  
    container_name: appserver     

  reverse_proxy:
    build: ./reverse_proxy
    ports: 
      - "8090:8090"
    networks:
      - front-tier
    volumes: 
      - /mnt/logs/nginx:/var/log/nginx   

  nginx_prometheus_exporter:
    build: ./nginx_prometheus_exporter
    command: nginx-prometheus-exporter -nginx.scrape-uri=http://reverse_proxy:8090/metrics  
    ports: 
      - "9113:9113"
    networks: 
      - front-tier  
    depends_on:
      - reverse_proxy  

  payment_gateway:
    build:
      context: payment_gateway
    networks:
      - payment
    secrets:
      - payment_token

networks:
  front-tier: 
  back-tier: 
  payment:
    driver: overlay  
    attachable: true
    

secrets:
  postgres_password:
    file: ./devsecrets/postgres_password
  payment_token:
    file: ./devsecrets/payment_token
