version: "3.1"

services:
  database:
    build: 
       context: ./database
    image: atsea_db
    command: postgres -c config_file=/usr/share/postgresql/9.6/postgresql.conf
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_DB: atsea
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432" 
    networks:
      - back-tier
    secrets:
      - postgres_password
    volumes: 
      - /mnt/logs/pg_log:/var/lib/postgresql/data/pg_log
        
  appserver:
    build:
       context: app
       dockerfile: Dockerfile-dev
    image: atsea_app
    ports:
      - "8080:8080"
      - "5005:5005"
      - "8099:8099"
    networks:
      - front-tier
      - back-tier
    secrets:
      - postgres_password
    volumes: 
      - /mnt/logs:/mnt/logs     

secrets:
  postgres_password:
    file: ./devsecrets/postgres_password
    
networks:
  front-tier:
  back-tier:
  payment:
    driver: overlay
